-- Migration 011: Add unified_profiles table for PPAL Identity Hub
-- Manages LINE / Teachable / Discord account linkage in a single table.
-- Run: wrangler d1 execute line-crm --file=packages/db/migrations/011_unified_profiles.sql --remote

CREATE TABLE IF NOT EXISTS unified_profiles (
  id                    TEXT PRIMARY KEY,              -- UUIDv4 generated by application (crypto.randomUUID())
  line_uid              TEXT UNIQUE NOT NULL,          -- LINE user ID (primary identity)
  teachable_id          INTEGER UNIQUE,                -- Teachable user ID (1:1 mapping)
  teachable_email       TEXT,                          -- Teachable registered email
  discord_id            TEXT UNIQUE,                   -- Discord user ID (1:1 mapping)
  discord_username      TEXT,                          -- Discord display name (informational)
  discord_roles         TEXT CHECK(discord_roles IS NULL OR json_valid(discord_roles)),  -- Granted roles (JSON array)
  teachable_linked_at   TEXT,                          -- Timestamp when Teachable account was linked
  discord_linked_at     TEXT,                          -- Timestamp when Discord account was linked
  created_at            TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at            TEXT DEFAULT (datetime('now'))
);

-- Only index columns without UNIQUE constraints (UNIQUE already creates an implicit index)
CREATE INDEX IF NOT EXISTS idx_unified_teachable_email ON unified_profiles(teachable_email);

-- Keep updated_at current on every UPDATE.
-- BEFORE UPDATE is used instead of AFTER UPDATE to avoid infinite recursion in D1.
-- SQLite disables recursive triggers (PRAGMA recursive_triggers=OFF) by default, so the
-- inner UPDATE statement inside this trigger will NOT re-fire this trigger.
-- Note: SQLite BEFORE triggers cannot modify NEW values directly (unlike PostgreSQL),
-- so an explicit UPDATE statement is required.
CREATE TRIGGER IF NOT EXISTS trg_unified_profiles_updated_at
  BEFORE UPDATE ON unified_profiles
BEGIN
  UPDATE unified_profiles SET updated_at = datetime('now') WHERE id = NEW.id;
END;
