-- Migration 011: Add unified_profiles table for PPAL Identity Hub
-- Manages LINE / Teachable / Discord account linkage in a single table.
-- Run: wrangler d1 execute line-crm --file=packages/db/migrations/011_unified_profiles.sql --remote

CREATE TABLE IF NOT EXISTS unified_profiles (
  id                    TEXT PRIMARY KEY,              -- UUIDv4 generated by application (crypto.randomUUID())
  line_uid              TEXT UNIQUE NOT NULL,          -- LINE user ID (primary identity)
  teachable_id          INTEGER UNIQUE,                -- Teachable user ID (1:1 mapping)
  teachable_email       TEXT,                          -- Teachable registered email
  discord_id            TEXT UNIQUE,                   -- Discord user ID (1:1 mapping)
  discord_username      TEXT,                          -- Discord display name (informational)
  discord_roles         TEXT,                          -- Granted roles (JSON array); application MUST validate json_valid()
  teachable_linked_at   TEXT,                          -- Timestamp when Teachable account was linked
  discord_linked_at     TEXT,                          -- Timestamp when Discord account was linked
  created_at            TEXT DEFAULT (datetime('now')),
  updated_at            TEXT DEFAULT (datetime('now'))
);

-- Only index columns without UNIQUE constraints (UNIQUE already creates an implicit index)
CREATE INDEX IF NOT EXISTS idx_unified_teachable_email ON unified_profiles(teachable_email);

-- Keep updated_at current on every UPDATE.
-- WHEN guard prevents infinite recursion: trigger fires only when updated_at was not explicitly changed.
CREATE TRIGGER IF NOT EXISTS trg_unified_profiles_updated_at
  AFTER UPDATE ON unified_profiles
  WHEN NEW.updated_at = OLD.updated_at
BEGIN
  UPDATE unified_profiles SET updated_at = datetime('now') WHERE id = NEW.id;
END;
